Rough Draft of Alasca Techtalk post
dd-ix/website-content pull request #12
Opened 2024-07-05 20:47 UTC by tanneberger

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +In den letzten Monaten ist viel passiert, das wichtigste unsere kern Infrastruktur steht.
```suggestion
In den letzten Monaten ist viel passiert, das Wichtigste, unsere Kerninfrastruktur steht. 
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +BGP Grundlagen, welche Funktion ein Internet Exchagen erfüllt und wie der DD-IX konstruiert wurde.
```suggestion
die Grundlagen von BGP, welche Funktion ein Internet Exchagen erfüllt und wie der DD-IX konstruiert wurde.
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +![Youtube Link](https://youtu.be/ieWTCBEq5IA)
```suggestion
Eine Aufzeichung findest du auf ![Youtube](https://youtu.be/ieWTCBEq5IA)!
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +Einige Tage später haben wir das [erste DD-IX Open Tech Meetup](https://dd-ix.net/en/event/open-tech-meeting-2024-05) durchgeführt. Wir haben uns sehr gefreut einen Teil der Dresdner Netzwerkcommunit
```suggestion
Ein paar Tage später fand das [erste DD-IX Open Tech Meetup](https://dd-ix.net/en/event/open-tech-meeting-2024-05) statt. Wir haben uns sehr gefreut einen Teil der Dresdner Netzwerkcommunity in den Räumlichkeiten der TU Dresden begrüsen zu können.
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +Wir bedanken uns hiermit ganz besonders bei [Thomas Liske](https://ibh.social/@liske) für die ausgezeichnete Präsentation über unsere Infrastruktur.
```suggestion
Wir bedanken uns hiermit ganz besonders bei [Thomas Liske](https://ibh.social/@liske) für die ausgezeichnete Präsentation unsere Infrastruktur.
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +Dannach gab es viele Ideen und Überlegungen, welche es bei Getränken und Snacks zu diskutieren galt.
```suggestion
Danach gab es bei Snacks und Getränken viele Anregungen und Diskusionen aller Beleiligten.
```

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +![](007_roundtable.webp)
Add alt text (text in the brackets)

2024-07-05 22:30 UTC, MarcelCoding commented on content/news/007.events-april-may-2024-05-17.de.md
> +Mitte Mai haben wir am BCIX Roundtable teilgenommen. Es war wieder ein Interessanter Abend mit Vorträgen und fröhlichen Austausch mit vielen bekannten und neuen Gesichern.
```suggestion
Zum Schluss haben wir mitte Mai am BCIX Roundtable teilgenommen. Es war wieder ein Interessanter Abend mit Vorträgen und fröhlichen Austausch mit vielen bekannten und neuen Gesichern.
```

2024-07-17 12:43 UTC, Nimuedaertya requested changes

2024-07-17 12:43 UTC, Nimuedaertya commented on content/blog/007.events-april-may-2024-05-17.de.md
> +die Grundlagen von BGP, welche Funktion ein Internet Exchagen erfüllt und wie der DD-IX konstruiert wurde.
Internet Exchange Point

2024-07-17 12:43 UTC, Nimuedaertya commented on content/blog/007.events-april-may-2024-05-17.de.md
> +Wir bedanken uns hiermit ganz besonders bei [Thomas Liske](https://ibh.social/@liske) für die ausgezeichnete Präsentation unser Infrastruktur.
unserer Infrastruktur

2024-07-17 12:43 UTC, Nimuedaertya commented on content/blog/007.events-april-may-2024-05-17.de.md
> +Mitte Mai haben wir am BCIX Roundtable teilgenommen. Es war wieder ein Interessanter Abend mit Vorträgen und fröhlichen Austausch mit vielen bekannten und neuen Gesichern.
interessanter
Gesichtern

2024-07-17 12:43 UTC, Nimuedaertya commented on content/blog/007.events-april-may-2024-05-17.en.md
> +BGP basics, which function an Internet Exchagen fulfils and how the DD-IX was constructed.
Internet Exchange points fulfills

2024-08-07 19:58 UTC, merged