Opening Post
dd-ix/website-content pull request #30
Opened 2024-12-17 22:05 UTC by tanneberger

2024-12-17 22:34 UTC, MarcelCoding approved these changes

2025-02-01 10:30 UTC, waehlisch requested changes
en-Variante gehe ich durch, wenn sie angepasst wurde.

2025-02-01 10:30 UTC, waehlisch commented on content/news/013.dd-ix-opening.de.md
> +Am 25. November feierten wir unsere offizielle Eröffnung mit Freunden des DD-IX's und lokalen Internetakteuren. Die Veranstaltung fand
DD-IX

2025-02-01 10:30 UTC, waehlisch commented on content/news/013.dd-ix-opening.de.md
> +Wir möchten uns bei unseren Vortragenden: Prof. Matthias Wählisch, Prof. Thomas Popp, Thomas Eibeck, Prof. Thomas Horn, Vint Cerf, Christian Dieckhoff,
Reihenfolge finde ich unguenstig. Alphabetisch statt in der Reihenfolge der Vortraege (die Reihenfolge kennt der Leser nicht). 

Hinter "Vortragenden" kein Doppelpunkt.

2025-02-01 10:30 UTC, waehlisch commented on content/news/013.dd-ix-opening.de.md
> +Marc Korthaus, Markus Ziehe, und Mirjam Kühne für ihre herausragenden Vorträge bedanken. Wir möchten uns auch bei allen bedanken, die uns im Hintergrund unterstützt haben, wie Thomas Wild,
Herzlichen Dank auch an die vielen Unterstützer im Hintergrund und die SachsenGigaBit GmbH für die Räumlichkeiten und Speis und Trank. Danke Thomas Wild, Kerstin Fiering und Tatjana Schiehandl für die tolle Zusammenarbeit bei der Organisation!

2025-02-01 10:30 UTC, waehlisch commented on content/news/013.dd-ix-opening.de.md
> +Kerstin Fiering oder Tatjana Schiehandl von der SachsenGigaBit GmbH, die uns auch ihre Räumlichkeiten zur Verfügung gestellt haben. Wir möchten uns auch bei Florian Hibler,
<Absatz>

Eine besondere Überraschung haben uns René Fichtmüller, Michael Nitsche, Thomas Weible, Sebastian Neuner, Tim Kleefass, Kurt Jaeger und Moritz Frenzel beschert: Zwei brandneue Arista-Switche, die uns bei der weiteren Entwicklung des DD-IX enorm helfen wird. Danke!

2025-02-01 10:30 UTC, waehlisch commented on content/news/013.dd-ix-opening.de.md
> +Es war eine großartige Erfahrung, euch alle nach Dresden einzuladen und mit euch diesen wichtig Schritt für den DD-IX zu feiern.
wir wollen nicht ueber unsere Erfahrungen berichten ;). Besser: Wir haben uns sehr gefreut, euch alle in Dresden begrüßen zu können und diesen für den DD-IX wichtigen Schritt mit euch gemeinsam zu feiern. Community at its best!

2025-02-04 06:36 UTC, tanneberger commented on content/news/013.dd-ix-opening.de.md
> +Am 25. November feierten wir unsere offizielle Eröffnung mit Freunden des DD-IX's und lokalen Internetakteuren. Die Veranstaltung fand
done

2025-02-04 06:37 UTC, tanneberger commented on content/news/013.dd-ix-opening.de.md
> +Wir möchten uns bei unseren Vortragenden: Prof. Matthias Wählisch, Prof. Thomas Popp, Thomas Eibeck, Prof. Thomas Horn, Vint Cerf, Christian Dieckhoff,
done, sorted by family name

2025-02-04 06:37 UTC, tanneberger commented on content/news/013.dd-ix-opening.de.md
> +Marc Korthaus, Markus Ziehe, und Mirjam Kühne für ihre herausragenden Vorträge bedanken. Wir möchten uns auch bei allen bedanken, die uns im Hintergrund unterstützt haben, wie Thomas Wild,
done

2025-02-04 06:37 UTC, tanneberger commented on content/news/013.dd-ix-opening.de.md
> +Kerstin Fiering oder Tatjana Schiehandl von der SachsenGigaBit GmbH, die uns auch ihre Räumlichkeiten zur Verfügung gestellt haben. Wir möchten uns auch bei Florian Hibler,
done

2025-02-04 06:37 UTC, tanneberger commented on content/news/013.dd-ix-opening.de.md
> +Es war eine großartige Erfahrung, euch alle nach Dresden einzuladen und mit euch diesen wichtig Schritt für den DD-IX zu feiern.
done

2025-02-04 06:39 UTC, tanneberger commented
I updated the English version accordingly.

2025-02-04 22:02 UTC, waehlisch requested changes

2025-02-04 22:04 UTC, merged